package io.github.waynem77.bscmail4.model.request;

import io.github.waynem77.bscmail4.model.entity.Person;
import io.github.waynem77.bscmail4.model.response.PersonResponse;
import org.junit.jupiter.api.Test;

import static io.github.waynem77.bscmail4.TestUtils.randomString;
import static org.junit.jupiter.api.Assertions.*;

class CreateOrUpdatePersonRequestTest
{
    @Test
    void createPersonReturnsCorrectValue()
    {
        // Arrange
        String name = randomString();
        String emailAddress = randomString() + "@example.com";
        String phone = randomString();
        Boolean active = true;

        CreateOrUpdatePersonRequest request = new CreateOrUpdatePersonRequest();
        request.setName(name);
        request.setEmailAddress(emailAddress);
        request.setPhone(phone);
        request.setActive(active);

        // Act
        Person person = request.createPerson();

        // Assert
        assertNotNull(person);
        assertNull(person.getId()); // ID should be null as it's generated by the database
        assertEquals(name, person.getName());
        assertEquals(emailAddress, person.getEmailAddress());
        assertEquals(phone, person.getPhone());
        assertTrue(person.getActive());
    }

    @Test
    void createPersonReturnsCorrectValueWithNullPhone()
    {
        // Arrange
        String name = randomString();
        String emailAddress = randomString() + "@example.com";
        Boolean active = false;

        CreateOrUpdatePersonRequest request = new CreateOrUpdatePersonRequest();
        request.setName(name);
        request.setEmailAddress(emailAddress);
        request.setPhone(null); // Test with null phone
        request.setActive(active);

        // Act
        Person person = request.createPerson();

        // Assert
        assertNotNull(person);
        assertNull(person.getId()); // ID should be null as it's generated by the database
        assertEquals(name, person.getName());
        assertEquals(emailAddress, person.getEmailAddress());
        assertNull(person.getPhone());
        assertFalse(person.getActive());
    }

    @Test
    void fromPersonResponseReturnsCorrectValue()
    {
        // Arrange
        Long id = 123L;
        String name = randomString();
        String emailAddress = randomString() + "@example.com";
        String phone = randomString();
        Boolean active = true;

        PersonResponse personResponse = new PersonResponse();
        personResponse.setId(id);
        personResponse.setName(name);
        personResponse.setEmailAddress(emailAddress);
        personResponse.setPhone(phone);
        personResponse.setActive(active);

        // Act
        CreateOrUpdatePersonRequest request = CreateOrUpdatePersonRequest.fromPersonResponse(personResponse);

        // Assert
        assertNotNull(request);
        assertEquals(name, request.getName());
        assertEquals(emailAddress, request.getEmailAddress());
        assertEquals(phone, request.getPhone());
        assertEquals(active, request.getActive());
        // Note: ID is not copied from PersonResponse to CreateOrUpdatePersonRequest
    }

    @Test
    void fromPersonResponseReturnsCorrectValueWithNullPhone()
    {
        // Arrange
        Long id = 456L;
        String name = randomString();
        String emailAddress = randomString() + "@example.com";
        Boolean active = false;

        PersonResponse personResponse = new PersonResponse();
        personResponse.setId(id);
        personResponse.setName(name);
        personResponse.setEmailAddress(emailAddress);
        personResponse.setPhone(null); // Test with null phone
        personResponse.setActive(active);

        // Act
        CreateOrUpdatePersonRequest request = CreateOrUpdatePersonRequest.fromPersonResponse(personResponse);

        // Assert
        assertNotNull(request);
        assertEquals(name, request.getName());
        assertEquals(emailAddress, request.getEmailAddress());
        assertNull(request.getPhone());
        assertEquals(active, request.getActive());
    }

    @Test
    void fromPersonResponseReturnsNullWhenInputIsNull()
    {
        // Arrange
        PersonResponse personResponse = null;

        // Act
        CreateOrUpdatePersonRequest request = CreateOrUpdatePersonRequest.fromPersonResponse(personResponse);

        // Assert
        assertNull(request);
    }

    @Test
    void fromPersonResponseHandlesAllNullFields()
    {
        // Arrange
        PersonResponse personResponse = new PersonResponse();
        personResponse.setId(null);
        personResponse.setName(null);
        personResponse.setEmailAddress(null);
        personResponse.setPhone(null);
        personResponse.setActive(null);

        // Act
        CreateOrUpdatePersonRequest request = CreateOrUpdatePersonRequest.fromPersonResponse(personResponse);

        // Assert
        assertNotNull(request);
        assertNull(request.getName());
        assertNull(request.getEmailAddress());
        assertNull(request.getPhone());
        assertNull(request.getActive());
    }
}