buildscript {
    ext {
        lombokVersion = '1.18.34'

        slf4jVersion = '2.0.16'

        springBootVersion = '3.3.4'
        springContextVersion = '6.1.13'

        postgresqlVersion = '42.7.4'

        jupiterVersion = '5.11.1'
        hamcrestVersion = '3.0'
        mockitoVersion = '5.14.0'
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
}

group 'io.github.waynem77'
version '4.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    compileOnly "org.slf4j:slf4j-api:${slf4jVersion}"
    implementation 'jakarta.validation:jakarta.validation-api:3.1.1'
    implementation "org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-thymeleaf:${springBootVersion}"
    implementation "org.springframework:spring-context:${springContextVersion}"
    implementation "org.postgresql:postgresql:${postgresqlVersion}"
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter-api:${jupiterVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter-params:${jupiterVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${jupiterVersion}"
    testImplementation "org.hamcrest:hamcrest:${hamcrestVersion}"
    testImplementation "org.mockito:mockito-core:${mockitoVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
    testImplementation 'com.h2database:h2:2.3.232'
}

test {
    useJUnitPlatform()
}

tasks.register("generateSql") {
    group = "application"
    description = "Runs the Spring Boot application with the dev profile"
    doFirst {
        tasks.bootRun.configure {
            systemProperty("spring.profiles.active", "generatesql")
        }
    }
    finalizedBy("bootRun")
}