package io.github.waynem77.bscmail4.model.request;

import io.github.waynem77.bscmail4.model.entity.Person;
import io.github.waynem77.bscmail4.model.response.PersonResponse;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

/**
 * Request DTO for creating or updating a Person.
 */
@Data
public class CreateOrUpdatePersonRequest
{

    @NotNull(message = "Name is required")
    @NotBlank(message = "Name is required")
    private String name;

    @NotNull(message = "Email address is required")
    @NotBlank(message = "Email address is required")
    @Email(message = "Email address must be valid")
    private String emailAddress;

    private String phone;

    @NotNull(message = "Active status is required")
    private Boolean active;

    /**
     * Creates a new Person entity from this request.
     * The id field will be null as it will be generated by the database.
     *
     * @return A new Person entity with the data from this request
     */
    public Person createPerson()
    {
        Person person = new Person();
        person.setName(this.name);
        person.setEmailAddress(this.emailAddress);
        person.setPhone(this.phone);
        person.setActive(this.active);
        return person;
    }

    /**
     * Creates a CreateOrUpdatePersonRequest from a PersonResponse.
     * Used for populating edit forms with existing person data.
     *
     * @param personResponse The PersonResponse to convert
     * @return A new CreateOrUpdatePersonRequest with data from the PersonResponse
     */
    public static CreateOrUpdatePersonRequest fromPersonResponse(PersonResponse personResponse)
    {
        if (personResponse == null)
        {
            return null;
        }

        CreateOrUpdatePersonRequest request = new CreateOrUpdatePersonRequest();
        request.setName(personResponse.getName());
        request.setEmailAddress(personResponse.getEmailAddress());
        request.setPhone(personResponse.getPhone());
        request.setActive(personResponse.getActive());
        return request;
    }
}
