create table person
(
    is_active     boolean                     not null,
    created_at    timestamp(6) with time zone not null,
    id            bigint generated by default as identity,
    email_address varchar(255)                not null,
    name          varchar(255)                not null,
    phone         varchar(255),
    primary key (id)
);
