create table person
(
    active        boolean      not null,
    id            bigint generated by default as identity,
    email_address varchar(255) not null,
    name          varchar(255) not null,
    phone         varchar(255),
    primary key (id)
);
